### ISSUE TITLE
`Pkg.test` in Jupyter notebook on Windows

### ISSUE THREAD

**Issue by oyamad** [OyamaZemi/exercises2017#10]
Test Summary が表示されない．

**Comment by oyamad** [comment]
Windows の人，パッケージのフォルダで Jupyter notebook を開いて

```jl
julia_exe = Base.julia_cmd()
run(`$julia_exe test/runtests.jl`)
```

を実行してみてください．

**Comment by ghost** [comment]
パッケージのフォルダとは、作ったパッケージの自分のPCにあるクローンのフォルダですよね。
実行してみたところ、エラーは出なかったのですが、何も表示されませんでした。
そのあとに `Pkg.test(”MyInterpolations")` を行っても、Summaryは表示されないままでした。

**Comment by ghost** [comment]
よく見たらコマンドプロンプト上にTest Summaryが表示されていました

**Comment by oyamad** [comment]
なるほど．
では Jupyter notebook で

```jl
run(`echo hello`)
```

としてみてください．

1. Notebook で `hello` と出ているか．
2. コマンドプロンプトの方で `hello` と出ているか．

**Comment by oyamad** [comment]
あとこれも：

```jl
ccall(:printf, Void, (Cstring,), "hello2\n")
```

1. Notebook で `hello2` と出ているか．
2. コマンドプロンプトの方で `hello2` と出ているか．

**Comment by ghost** [comment]
`run(`echo hello`)` を実行してみたところ、
`` could not spawn `echo hello`: no such file or directory (ENOENT) ``
とエラーが出ました。
詳しくは全然わからないのですが、Windowsだとbulit-inがどうとかで、これだとエラーになるみたいです。

` run(`cmd /C echo hello`) `と変えて実行したら、コマンドプロンプト上に表示されました。

``ccall(:printf, Void, (Cstring,), "hello2\n")`` もコマンドプロンプト上に表示されました

**Comment by oyamad** [comment]
エラーが出ない方および `ccall` で「コマンドプロンプト上に表示されました」というのは「notebook では表示されませんでした」というのを含意しているのですか．

**Comment by ghost** [comment]
はい、どちらもnotebookでは表示されず、コマンドプロンプト上でのみ表示されました。

**Comment by oyamad** [comment]
では

```jl
println(STDOUT, "hello3")
```

と

```jl
println(STDERR, "hello4")
```

はそれぞれどうですか．

1. Notebook で `hello3` あるいは `hello4` と出ているか．
2. コマンドプロンプトの方で `hello3` あるいは `hello4` と出ているか．

**Comment by ghost** [comment]
どちらもnotebook上でのみ表示されました

**Comment by oyamad** [comment]
なるほど．そうすると，

* 外部コマンドの (おそらく `stdout` への) 出力は notebook ではなくコマンドプロンプトにつながっている
* Julia コマンドの `stdout`/`stderr` は notebook につながっている

ということのようですね．

[IJulia.jl](https://github.com/JuliaLang/IJulia.jl) の Issues に書いてあげた方がよいと思いますが，できますか @EikiTakigawa

**Comment by ghost** [comment]
`stdout` など、notebookに表示できるときとできないときの違いが理解できていなくて、ちゃんと報告できそうにないのですが…

**Comment by oyamad** [comment]
何でも経験だからやってみましょう．

* ``Pkg.test(”MyInterpolations")`` を Jupyter notebook 上で実行しても，"Test Summary" が notebook 上には print されず，cmd.exe の方のみに print された．(MyInterpolations ではなく何かポピュラーなパッケージの方がよいけど，まあいいでしょう．)
* 試しに ``run(`cmd /C echo hello`)`` と ``ccall(:printf, Void, (Cstring,), "hello2\n")`` とを実行してみても，同様に notebook 上には print されず，cmd.exe の方のみに print された．どうすれば notebook に出ますか？と聞く．
* Julia での ``versioninfo()`` の出力をコピーペーストする．
* Julia での ``Pkg.installed("IJulia")`` の出力をコピーペーストする．

私にも `@oyamad` で Cc しておいてください．

**Comment by oyamad** [comment]
敷居が低いのはこっち https://github.com/JuliaTokyo/julia-wakalang かな．

**Comment by ghost** [comment]
やってみます。
Macだと、`` run(`cmd /C echo hello`) `` と ` ccall(:printf, Void, (Cstring,), "hello2\n") ` を実行すると notebook上に出るのですか？

**Comment by oyamad** [comment]
そうです，Mac だと notebook 上にのみ出ます．(前者は ``run(`echo hello`)`` ですが．)

**Comment by ghost** [comment]
分かりました。ありがとうございます

**Comment by oyamad** [comment]
https://github.com/OyamaZemi/exercises2017/pull/42#issuecomment-312186524 で，Julia v0.6 にしたら `Pkg.test` の Test Summary は notebook に表示されるようになったとのことですが，同じく v0.6 で

1. ``run(`cmd /C echo hello`)``
2. ``ccall(:printf, Void, (Cstring,), "hello2\n")``

を notebook 上で実行するとどうなりますか．

**Comment by ghost** [comment]
どちらも notebook 上にのみ表示されました

**Comment by oyamad** [comment]
0.6 では直ったということなので閉じます．
