### ISSUE TITLE
Ex03

### ISSUE THREAD

**Issue by oyamad** [OyamaZemi/exercises2017#31]
担当希望をここに書いてください．

**Comment by m21kosumi** [comment]
7.6.2を希望します。

**Comment by NTsuchiya0127** [comment]
7.6.3を希望します。

**Comment by ghost** [comment]
7.6.6を希望します

**Comment by R-Tsushima** [comment]
7.6.5を希望します。

**Comment by nswa17** [comment]
Markov Chainのjuliaへの翻訳を希望します。

**Comment by oyamad** [comment]
~~改訂中のノートブックは[ここ](https://github.com/oyamad/QuantEcon.notebooks/tree/MF_rev)にあります．~~ [本家](https://github.com/QuantEcon/QuantEcon.notebooks)にマージされました．

**Comment by IoriS** [comment]
担当
* [x] 1 齊藤、高橋
* [x] 2 池上、小住 
* [x] 3 松下、土屋
* [x] 4 森、佐々木
* [x] 5 津島、優
* [x] 6 瀧川、金
* [x] 7(MC) 中田、金丸

です。

**Comment by oyamad** [comment]
* そろそろ締切です．できたところまでの notebook を自分の [QuantEcon.notebooks](https://github.com/QuantEcon/QuantEcon.notebooks) のフォークにプッシュして，お互い参考にできるようにしましょう．その際，`master` 以外の新しいブランチを作ってそこにプッシュするように．
* わからないことがあったらここに書いてください．

**Comment by oyamad** [comment]
まだの人は早めにやりましょう．QuantEcon.notebooks は近いうちに閉じられるそうです．
